version: 0.0
os: linux
files:
 - source: /
   destination: /var/www/learn-app/html
hooks:
  BeforeInstall:
    - location: scripts/codedeploy-prepare.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/codedeploy-setup-app.sh
      timeout: 300
      runas: root